name: campus_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+7

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  crypto: ^3.0.6
  data_table_2: ^2.5.15
  shared_preferences: ^2.3.4
  multi_select_flutter: ^4.1.3
  fluttertoast: ^8.2.10
  intl: ^0.20.1
  flutter_launcher_icons: ^0.14.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  fl_chart: ^0.70.2
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:

    - assets/images/CampusConnect large(1).png
    - assets/images/CampusConnectsmall.png
    - assets/images/CampusConnectmedium.png
    - assets/images/CampusConnect largeWhite.png
    - assets/images/ForgotPasswordLarge.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/CampusConnectsmall.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/CampusConnectsmall.png"
